import "./globals.css";
import { Roboto } from 'next/font/google'
import Navbar from '@/components/landing/Navbar';
import Footer from '@/components/landing/Footer';
import { AuthProvider } from '@/utils/hooks/useAuth';

export const metadata = {
  title: "Clinica Homeopática",
  keywords: ["homeopatía", "salud", "bienestar", "medicina alternativa"],
  authors: [{ name: "Clinica Homeopática" }],
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  variable: '--font-roboto', 
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={` antialiased`} >
        <AuthProvider>
          <Navbar/>
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
